# Generated by Django 5.2.3 on 2025-07-13 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tier_type', models.CharField(choices=[('FREE', 'Home Cook'), ('STARTER', 'Sous Chef'), ('PREMIUM', 'Master Chef')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('features', models.JSONField(default=list)),
                ('max_shared_menus', models.IntegerField(default=0, help_text='0 means unlimited for paid tiers, none for free')),
                ('max_menu_days', models.IntegerField(default=7, help_text='Maximum days for menu planning')),
                ('max_recipes', models.IntegerField(default=-1, help_text='-1 means unlimited')),
                ('max_menus', models.IntegerField(default=-1, help_text='-1 means unlimited')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MicrosoftOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Encrypted access token for Microsoft Graph API')),
                ('refresh_token', models.TextField(help_text='Encrypted refresh token for token renewal')),
                ('token_expires', models.DateTimeField(help_text='When the access token expires')),
                ('calendar_sync_enabled', models.BooleanField(default=True, help_text='Whether calendar sync is enabled for this user')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time calendar was synchronized', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Microsoft OAuth Token',
                'verbose_name_plural': 'Microsoft OAuth Tokens',
                'db_table': 'auth_hub_microsoft_oauth_token',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_tier_change_date', models.DateTimeField(blank=True, help_text='Date when the tier change will take effect', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trial', 'Trial'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_updated_at', models.DateTimeField(auto_now=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('menus_created', models.IntegerField(default=0)),
                ('recipes_saved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_subscription_tier', models.ForeignKey(blank=True, help_text='Tier to switch to at the end of billing period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_profiles', to='auth_hub.subscriptiontier')),
                ('subscription_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='auth_hub.subscriptiontier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('subscription_change', 'Subscription Change'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_downgraded', 'Subscription Downgraded'), ('subscription_downgrade_scheduled', 'Downgrade Scheduled'), ('subscription_downgrade_cancelled', 'Downgrade Cancelled'), ('menu_shared', 'Menu Shared'), ('menu_accepted', 'Menu Share Accepted'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='auth_hub_ac_user_id_050d92_idx'), models.Index(fields=['action', '-created_at'], name='auth_hub_ac_action_0c066f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_reshare', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_menus', to=settings.AUTH_USER_MODEL)),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Share',
                'verbose_name_plural': 'Menu Shares',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'shared_with_email')},
            },
        ),
    ]
