# Generated by Django 5.2.3 on 2025-06-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='max_menus',
            field=models.IntegerField(default=-1, help_text='-1 means unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='max_recipes',
            field=models.IntegerField(default=-1, help_text='-1 means unlimited'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_subscription_tier',
            field=models.ForeignKey(blank=True, help_text='Tier to switch to at the end of billing period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_profiles', to='auth_hub.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_tier_change_date',
            field=models.DateTimeField(blank=True, help_text='Date when the tier change will take effect', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('subscription_change', 'Subscription Change'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_downgraded', 'Subscription Downgraded'), ('subscription_downgrade_scheduled', 'Downgrade Scheduled'), ('subscription_downgrade_cancelled', 'Downgrade Cancelled'), ('menu_shared', 'Menu Shared'), ('menu_accepted', 'Menu Share Accepted'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='max_shared_menus',
            field=models.IntegerField(default=0, help_text='0 means unlimited for paid tiers, none for free'),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
