# Generated by Django 5.2.3 on 2025-06-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_hub", "0002_subscriptiontier_max_menus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MicrosoftOAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Encrypted access token for Microsoft Graph API"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        help_text="Encrypted refresh token for token renewal"
                    ),
                ),
                (
                    "token_expires",
                    models.DateTimeField(help_text="When the access token expires"),
                ),
                (
                    "calendar_sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether calendar sync is enabled for this user",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time calendar was synchronized",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microsoft_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Microsoft OAuth Token",
                "verbose_name_plural": "Microsoft OAuth Tokens",
                "db_table": "auth_hub_microsoft_oauth_token",
            },
        ),
    ]
