# Generated by Django 4.2.23 on 2025-06-29 09:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsdaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the category", max_length=255
                    ),
                ),
                (
                    "url_code",
                    models.CharField(
                        help_text="Numeric code used in ASDA URLs",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category should be included in scraping",
                    ),
                ),
                (
                    "last_crawled",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this category was scraped",
                        null=True,
                    ),
                ),
                (
                    "product_count",
                    models.IntegerField(
                        default=0, help_text="Number of products found in this category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category if this is a subcategory",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="asda_scraper.asdacategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASDA Category",
                "verbose_name_plural": "ASDA Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CrawlSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("categories_crawled", models.IntegerField(default=0)),
                ("products_found", models.IntegerField(default=0)),
                ("products_updated", models.IntegerField(default=0)),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Any errors encountered during crawling"
                    ),
                ),
                (
                    "crawl_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration used for this crawl session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawl Session",
                "verbose_name_plural": "Crawl Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AsdaProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name as shown on ASDA website",
                        max_length=500,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current price in pounds",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., 'each', 'kg', '100g')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Product description"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="URL to product image"),
                ),
                (
                    "product_url",
                    models.URLField(
                        help_text="Direct URL to product page on ASDA", unique=True
                    ),
                ),
                (
                    "asda_id",
                    models.CharField(
                        help_text="ASDA's internal product ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        default=True, help_text="Whether product is currently available"
                    ),
                ),
                (
                    "special_offer",
                    models.CharField(
                        blank=True,
                        help_text="Any special offer or promotion text",
                        max_length=200,
                    ),
                ),
                (
                    "nutritional_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Nutritional information if available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="asda_scraper.asdacategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASDA Product",
                "verbose_name_plural": "ASDA Products",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["asda_id"], name="asda_scrape_asda_id_180bb3_idx"
                    ),
                    models.Index(
                        fields=["category", "name"],
                        name="asda_scrape_categor_1b012c_idx",
                    ),
                    models.Index(fields=["price"], name="asda_scrape_price_6b466c_idx"),
                ],
            },
        ),
    ]
