# Generated by Django 4.2.23 on 2025-06-29 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asda_scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asdaproduct",
            name="price_per_unit",
            field=models.CharField(
                blank=True,
                help_text="Price per unit string (e.g., '£6.83/kg')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="asdaproduct",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Product rating out of 5 stars",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="asdaproduct",
            name="review_count",
            field=models.CharField(
                blank=True,
                help_text="Number of reviews (e.g., '50+', '127')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asdaproduct",
            name="was_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price if item is on sale",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="asdaproduct",
            name="special_offer",
            field=models.CharField(
                blank=True,
                help_text="Any special offer or promotion text (e.g., 'Rollback')",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="asdaproduct",
            index=models.Index(fields=["rating"], name="asda_scrape_rating_b86616_idx"),
        ),
        migrations.AddIndex(
            model_name="asdaproduct",
            index=models.Index(
                fields=["was_price"], name="asda_scrape_was_pri_5cbf10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asdaproduct",
            index=models.Index(
                fields=["special_offer"], name="asda_scrape_special_2a3f79_idx"
            ),
        ),
    ]
