# Generated by Django 5.2.3 on 2025-07-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asda_scraper', '0002_proxyconfiguration_proxyprovidersettings_and_more'),
        ('asda_scraper', '0003_add_crawl_type'),
    ]

    operations = [
    ]
