# Generated by Django 5.2.3 on 2025-06-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_planner", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outlook_event_id",
                    models.CharField(
                        help_text="ID of the event in Outlook calendar", max_length=255
                    ),
                ),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending Sync"),
                            ("error", "Sync Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True, help_text="Error message if sync failed"
                    ),
                ),
                (
                    "meal_slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_event",
                        to="meal_planner.mealslot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meal_planner_calendar_event",
                "indexes": [
                    models.Index(
                        fields=["outlook_event_id"],
                        name="meal_planne_outlook_4953cc_idx",
                    ),
                    models.Index(
                        fields=["sync_status"], name="meal_planne_sync_st_212697_idx"
                    ),
                ],
                "unique_together": {("meal_slot", "user")},
            },
        ),
    ]
