# Generated by Django 5.2.3 on 2025-07-13 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_planner', '0001_initial'),
        ('recipe_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplantemplateslot',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='recipe_hub.recipe'),
        ),
        migrations.AddField(
            model_name='mealplantemplateslot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='meal_planner.mealplantemplate'),
        ),
        migrations.AddField(
            model_name='mealslot',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='meal_planner.mealplan'),
        ),
        migrations.AddField(
            model_name='mealslot',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_slots', to='recipe_hub.recipe'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='meal_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event', to='meal_planner.mealslot'),
        ),
        migrations.AddField(
            model_name='mealslot',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_slots', to='meal_planner.mealtype'),
        ),
        migrations.AddField(
            model_name='mealplantemplateslot',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_slots', to='meal_planner.mealtype'),
        ),
        migrations.AddField(
            model_name='recipecsvupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mealplantemplate',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['owner', '-start_date'], name='meal_planne_owner_i_492435_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['start_date', 'end_date'], name='meal_planne_start_d_57fbc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['outlook_event_id'], name='meal_planne_outlook_4953cc_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['sync_status'], name='meal_planne_sync_st_212697_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('meal_slot', 'user')},
        ),
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['meal_plan', 'date'], name='meal_planne_meal_pl_266bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='mealslot',
            index=models.Index(fields=['date'], name='meal_planne_date_1605b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealslot',
            unique_together={('meal_plan', 'date', 'meal_type')},
        ),
        migrations.AlterUniqueTogether(
            name='mealplantemplateslot',
            unique_together={('template', 'day_offset', 'meal_type')},
        ),
    ]
