# Generated by Django 4.2.23 on 2025-06-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe_hub", "0004_alter_ingredient_order_alter_ingredient_unit"),
        ("meal_planner", "0003_recipecsvupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealslot",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_slots",
                to="recipe_hub.recipe",
            ),
        ),
    ]
