# Generated by Django 4.2.23 on 2025-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_planner", "0002_calendarevent"),
        ("recipe_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="meal_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="What meals is this recipe suitable for? (breakfast, lunch, dinner, snack)",
                related_name="recipes",
                to="meal_planner.mealtype",
            ),
        ),
    ]
