# Generated by Django 4.2.23 on 2025-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe_hub", "0003_ingredientcategory_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                blank=True, help_text="e.g., cups, tbsp, oz", max_length=50
            ),
        ),
    ]
